spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888  # Make the config server optional

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true # enable routing based on service discovery

# below lines can be used, but can be added to the config server's api-gateway.yml file
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/product-service/**
#          filters:
#            - RewritePath=/product-service/(?<remaining>.*), /${remaining}
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - RewritePath=/order-service/(?<remaining>.*), /${remaining}
#        - id: customer-service
#          uri: lb://customer-service
#          predicates:
#            - Path=/customer-service/**
#          filters:
#            - RewritePath=/customer-service/(?<remaining>.*), /${remaining}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG