spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888  # Make the config server optional

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    root: DEBUG
