spring:
  application:
    name: product-service
  cloud:
    config:
      uri: http://localhost:8888  # Your config-server URL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL

server:
  port: 8081  # Port for Product Service

management:
  endpoints:
    web:
      exposure:
        include: "*"
