spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8888  # Make the config server optional

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false